# Site configuration for new.andersaamodt.com
template=blog
nostr_bridge_enabled=true
site-name=new.andersaamodt.com
site-user=new_andersaamodt_com
plugin_nostr_support=true
plugin_nostr_login=true
plugin_nostr_bridge=true
plugin_nostr_posts=true
plugin_zaps=true
plugin_btcpay=true
registration_enabled=true
site_title=Anders' Blog
theme=lapidarist
drip_interval_hours=4
drip_interval_minutes=240
drip_randomness_minutes=0
drip_jitter_minutes=0
feed_full_text=true
feed_items=50
append_site_title_to_page_title=false
new_users_are_admins=false
zaps_enabled=true
zap_default_amount_sats=1000
btcpay_host=pay.andersaamodt.com
btcpay_rootpath=/
lightning_public_host=pay.andersaamodt.com
zap_alias_name=zap
zap_alias_domain=andersaamodt.com
port=8093
domain=new.andersaamodt.com
https=true
zap_lud16=zap@andersaamodt.com
secure_chat_native_driver_enabled=true
plugin_video_chat=true
plugin_overworld=true
overworld_anonymous_enabled=true
overworld_anonymous_time_limit_seconds=900
overworld_show_hidden=false
overworld_access_mode=player
overworld_max_entries=96
