#!/bin/sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname "$0")" && pwd -P)
SITE_SOURCE_ROOT="$ROOT_DIR/site"

PASS_COUNT=0
FAIL_COUNT=0

pass() {
  PASS_COUNT=$((PASS_COUNT + 1))
}

fail() {
  FAIL_COUNT=$((FAIL_COUNT + 1))
  printf 'FAIL: %s\n' "$1" >&2
}

assert_file_contains() {
  file=$1
  needle=$2
  label=$3
  if grep -Fq "$needle" "$file"; then
    pass
  else
    fail "$label (missing: $needle in $file)"
  fi
}

assert_file_not_contains() {
  file=$1
  needle=$2
  label=$3
  if grep -Fq "$needle" "$file"; then
    fail "$label (unexpected: $needle in $file)"
  else
    pass
  fi
}

# Backend: draft/publish post_type plumbing.
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'blog_normalize_post_type() {' 'post_type normalizer exists'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'case "$raw" in' 'normalizer uses explicit case mapping'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'blog_iso_to_human_timestamp() {' 'post date hover timestamp formatter exists'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" "at %I:%M:%S %p UTC" 'post date hover formatter emits long timestamp text'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" "short|shortform)" 'normalizer supports shortform aliases'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" "''|long|longform)" 'normalizer defaults empty/long aliases to longform'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'capture|capture-media|capture_media|take-photo|take-photo-video)' 'normalizer supports capture-media aliases'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'media|media-upload|media_upload|upload-media|upload_media|photo|video|image)' 'normalizer supports upload-media aliases'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'attachment|attachments|file|file-upload|file_upload)' 'normalizer supports attachment aliases'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'audio|audio-note|audio_note|voice|voice-note|voice_note)' 'normalizer supports audio-note aliases'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'link|link-share|link_share|url|share-link)' 'normalizer supports link-share aliases'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'post_type=${14-longform}' 'draft writer defaults post_type to longform'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'post_type=$(blog_normalize_post_type "$post_type")' 'draft writer normalizes post_type'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'printf '\''post_type: "%s"\n'\'' "$(blog_yaml_escape "$post_type")"' 'draft front matter stores post_type'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'normalized_post_type=$(blog_normalize_post_type "$post_type")' 'save draft normalizes post_type before write'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'if [ "$normalized_post_type" = "shortform" ]; then' 'save draft/publish markdown guard shortform title behavior'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" "title=''" 'shortform guard clears title field'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'd_seed=$(blog_slug_seed_text "$title" "$content" "$post_type")' 'nostr d-tag seed can derive from body content'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'blog_write_draft_markdown "$draft_file"' 'save draft writes markdown with post_type'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'post_type=${9-longform}' 'publish markdown defaults post_type to longform'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'printf '\''post_type: "%s"\n'\'' "$(blog_yaml_escape "$normalized_post_type")"' 'publish front matter stores normalized post_type'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'post_type=$(blog_read_front_matter_value "$draft_file" post_type' 'queue reads draft post_type'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'blog_publish_content "$title" "$tags" "$summary" "$content" "$author" "$draft_id" scheduled "$now_iso" "$post_type"' 'scheduled publish forwards post_type'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'blog_publish_content "$title" "$tags" "$summary" "$content" "$author" "$draft_id" drip "" "$post_type"' 'drip publish forwards post_type'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'blog_nostr_kind_for_post_type() {' 'nostr kind resolver exists'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'shortform|link-share)' 'nostr kind resolver maps shortform/link-share to kind 1'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'attachment)' 'nostr kind resolver maps attachment post type'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" "printf '15\\n'" 'nostr kind resolver emits kind 15 for attachment'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" "printf '30311\\n'" 'nostr kind resolver emits kind 30311 for go-live'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'post_type=$post_type' 'nostr signer tags event with normalized post_type'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" '.kind==1 or .kind==15 or .kind==20 or .kind==21 or .kind==30023 or .kind==30311' 'derived rebuild includes non-longform nostr kinds'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'post_type_tag:' 'derived rebuild reads post_type tag from nostr events'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'post_type: (' 'derived rebuild writes post_type in posts index'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'set -- nak req -k 1 -k 15 -k 20 -k 21 -k 30311 -t "t=blog"' 'mirror fetch includes non-longform kinds constrained by blog tag'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'printf '\''%s:%s:%s\n'\'' "$ref_kind" "$ref_pubkey" "$ref_d"' 'list event a-ref preserves referenced post kind'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'published_timestamp: $published_timestamp' 'public posts catalog exposes long hover timestamp when available'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'blog_post_header_meta_html()' 'server renderers share post header metadata template'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" 'safe_date_title_attr=" title=\"$safe_timestamp\""' 'shared post header metadata template preserves date hover title attribute'
assert_file_contains "$ROOT_DIR/cgi/blog-lib.sh" '<div class="post-head-divider" aria-hidden="true"></div>' 'shared post header metadata template keeps byline below divider'
assert_file_contains "$ROOT_DIR/cgi/blog-index" 'post_header_meta_html=$(blog_post_header_meta_html "$author" "$reading_minutes" "$pub_date" "$published_timestamp")' 'fallback blog feed uses shared post header metadata template'
assert_file_contains "$ROOT_DIR/cgi/blog-open-post" 'post_header_meta_html=$(blog_post_header_meta_html "$author" "$reading_minutes" "$published_date" "$published_timestamp")' 'single post fallback uses shared post header metadata template'
assert_file_contains "$ROOT_DIR/cgi/blog-post-context" 'printf '\''"published_timestamp":"%s",'\'' "$(blog_json_escape "$published_timestamp")"' 'post context endpoint exposes long hover timestamp'

# Backend endpoints: save/get/move preserve post_type.
assert_file_contains "$ROOT_DIR/cgi/blog-save-post" 'post_type=$(blog_param post_type)' 'save endpoint reads post_type param'
assert_file_contains "$ROOT_DIR/cgi/blog-save-post" 'publish_destination=$(blog_param publish_destination)' 'save endpoint reads publish destination param'
assert_file_contains "$ROOT_DIR/cgi/blog-save-post" 'post_type=$(blog_read_front_matter_value "$draft_file" post_type' 'save endpoint falls back to draft post_type'
assert_file_contains "$ROOT_DIR/cgi/blog-save-post" 'post_type=$(blog_read_front_matter_value "$draft_file" type' 'save endpoint supports legacy type fallback'
assert_file_contains "$ROOT_DIR/cgi/blog-save-post" 'post_type=$(blog_normalize_post_type "$post_type")' 'save endpoint normalizes post_type'
assert_file_contains "$ROOT_DIR/cgi/blog-save-post" 'blog_publish_content_markdown "$title" "$normalized_tags" "$summary" "$content" "$author_name" "$draft_id" immediate "" "$post_type"' 'server publish forwards post_type to markdown publisher'
assert_file_contains "$ROOT_DIR/cgi/blog-save-post" 'blog_publish_content_nostr "$title" "$normalized_tags" "$summary" "$content" "$author_name" "$draft_id" immediate "" "$post_type"' 'nostr publish forwards post_type to nostr publisher'
assert_file_contains "$ROOT_DIR/cgi/blog-save-post" 'blog_save_draft "$draft_id" "$title" "$normalized_tags" "$summary" "$content" "$author_name" scheduled "$scheduled_at" scheduled "$post_type"' 'scheduled draft saves post_type'
assert_file_contains "$ROOT_DIR/cgi/blog-save-post" 'blog_save_draft "$draft_id" "$title" "$normalized_tags" "$summary" "$content" "$author_name" drip "" queued "$post_type"' 'drip draft saves post_type'
assert_file_contains "$ROOT_DIR/cgi/blog-save-post" 'blog_save_draft "$draft_id" "$title" "$normalized_tags" "$summary" "$content" "$author_name" "$publish_mode" "$scheduled_at" "$status" "$post_type"' 'autosave draft saves post_type'
assert_file_contains "$ROOT_DIR/cgi/blog-get-draft" 'post_type=$(blog_read_front_matter_value "$draft_file" post_type' 'get draft reads post_type'
assert_file_contains "$ROOT_DIR/cgi/blog-get-draft" 'post_type=$(blog_read_front_matter_value "$draft_file" type' 'get draft supports legacy type fallback'
assert_file_contains "$ROOT_DIR/cgi/blog-get-draft" 'printf '\''"post_type":"%s",'\'' "$(blog_json_escape "$post_type")"' 'get draft emits post_type field'
assert_file_contains "$ROOT_DIR/cgi/blog-create-draft-from-post" 'post_type=$(blog_read_front_matter_value "$file" post_type' 'create draft from post carries post_type'
assert_file_contains "$ROOT_DIR/cgi/blog-create-draft-from-post" 'post_type=$(blog_read_front_matter_value "$file" type' 'create draft supports legacy type fallback'
assert_file_contains "$ROOT_DIR/cgi/blog-create-draft-from-post" 'blog_save_draft "$draft_id" "$title" "$tags" "$summary" "$content" "$author" draft "" draft "$post_type"' 'create draft persists post_type'
assert_file_contains "$ROOT_DIR/cgi/blog-unqueue-draft" 'post_type=$(blog_read_front_matter_value "$draft_file" post_type' 'unqueue reads draft post_type'
assert_file_contains "$ROOT_DIR/cgi/blog-unqueue-draft" 'post_type=$(blog_read_front_matter_value "$draft_file" type' 'unqueue supports legacy type fallback'
assert_file_contains "$ROOT_DIR/cgi/blog-unqueue-draft" 'blog_save_draft "$draft_id" "$title" "$tags" "$summary" "$content" "$author" draft "" draft "$post_type"' 'unqueue keeps post_type when restoring draft'

# Admin compose markup.
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'id="compose-post-type-toolbar"' 'admin compose has post type toolbar'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'data-post-type="shortform"' 'admin compose shortform pill'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'data-post-type="longform"' 'admin compose longform pill'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'data-post-type="capture-media"' 'admin compose capture-media pill'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'data-post-type="upload-media"' 'admin compose upload-media pill'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'data-post-type="attachment"' 'admin compose attachment pill'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'data-post-type="audio-note"' 'admin compose audio-note pill'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'data-post-type="link-share"' 'admin compose link-share pill'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'data-post-type="go-live"' 'admin compose go-live pill'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'class="compose-post-type-icon"' 'admin compose pills render icon-only controls'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'aria-label="Shortform Post"' 'admin icon-only control keeps accessible label'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'title="Coming soon: Go Live"' 'admin disabled go-live icon has tooltip'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'id="compose-media-tools"' 'admin compose media tools block'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'id="compose-nostr-target-pill"' 'admin compose renders nostr target pill'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'id="btn-compose-capture"' 'admin compose capture button'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'id="btn-compose-upload-media"' 'admin compose upload-media button'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'id="btn-compose-upload-file"' 'admin compose attachment button'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'id="btn-compose-upload-audio"' 'admin compose audio button'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'id="compose-link-fields"' 'admin compose link-share fields container'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'id="compose-link-url"' 'admin compose link URL field'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'id="compose-link-body"' 'admin compose link body field'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'id="compose-shortform-meter"' 'admin compose renders shortform counter row'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'id="btn-compose-shortform-limit"' 'admin compose shortform counter toggle button'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'id="compose-shortform-limit-input"' 'admin compose shortform custom limit input'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'id="capture-picker"' 'admin compose capture picker exists'
assert_file_contains "$SITE_SOURCE_ROOT/pages/admin.md" 'id="audio-picker"' 'admin compose audio picker exists'

# Admin compose runtime behavior.
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" "const COMPOSE_POST_TYPES = ['shortform', 'longform', 'capture-media', 'upload-media', 'attachment', 'audio-note', 'link-share', 'go-live'];" 'admin js defines full post type set'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" "const COMPOSE_POST_TYPES_ENABLED = ['shortform', 'longform', 'capture-media', 'upload-media', 'attachment', 'audio-note', 'link-share'];" 'admin js keeps go-live disabled'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'if (type === '\''go-live'\'') { return '\''go live'\''; }' 'admin js labels go-live'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" "setOutput(els.outputCompose, 'Go Live is a future feature.', 'warn');" 'admin js surfaces go-live disabled message'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'els.composeMediaTools.hidden = !showMedia;' 'admin js toggles media tool visibility by type'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'els.composeLinkFields.hidden = !linkShare;' 'admin js toggles link fields visibility'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'composeShortformLimit: 280,' 'admin js tracks shortform limit state'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'function setComposeShortformLimit(raw, opts) {' 'admin js supports editable shortform limits'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'els.postContent.rows = 11;' 'admin shortform textarea uses reduced height'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" "els.composeShortformLimitButton.addEventListener('dblclick'" 'admin shortform limit supports custom edit mode'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'function composeNostrTarget(postType) {' 'admin js defines nostr target mapper for compose'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'els.composeNostrTargetPill.textContent = label;' 'admin js updates nostr target pill when post type changes'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'post_type: postType,' 'admin compose payload includes post_type'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" "title: postType === 'shortform' ? '' : titleValue," 'admin compose sends empty title for shortform payloads'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'titleRow.hidden = !showTitleField;' 'admin compose hides title row for shortform'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'state.composePostType = normalizeComposePostType((draft && draft.post_type) || '\''longform'\'');' 'admin draft load hydrates post_type'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'state.composePostType = '\''longform'\'';' 'admin compose reset restores longform default'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'composeSubmitInFlight: false' 'admin compose tracks publish submit in-flight state'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" "els.publishNowButton.textContent = 'Publishing...';" 'admin compose publish button gives immediate busy feedback'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'els.publishNowButton.disabled = true;' 'admin compose publish button disables during submit'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'if (state.composeSubmitInFlight) {' 'admin compose publish click ignores duplicate submits'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'state.suspendAutosave || state.composeSubmitInFlight' 'admin compose autosave pauses during explicit submit'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" "if (event.key === 'Tab' || event.key === ',')" 'admin compose tag editor only finalizes token input on tab or comma'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'composeTagsEditor.addEventListener('\''focusout'\'', function () {' 'admin compose tag editor handles blur without tokenizing draft text'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'composeTagsEditorSyncDraft(composeTagsEditor);' 'admin compose tag blur syncs draft text only'
assert_file_not_contains "$SITE_SOURCE_ROOT/static/admin.js" "if (event.key === 'Enter' || event.key === ',')" 'admin compose tag editor no longer finalizes tags on enter'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'const tagEditor = composeTagsEditorNode();' 'admin compose payload read syncs tag draft without tokenizing it'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'setComposePostType('\''capture-media'\'', { queueAutosave: false, syncUi: true });' 'admin capture button selects capture-media'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'setComposePostType('\''upload-media'\'', { queueAutosave: false, syncUi: true });' 'admin upload-media button selects upload-media'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'setComposePostType('\''attachment'\'', { queueAutosave: false, syncUi: true });' 'admin attachment button selects attachment'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'setComposePostType('\''audio-note'\'', { queueAutosave: false, syncUi: true });' 'admin audio button selects audio-note'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'state.filePickerContext = '\''compose-attachment'\'';' 'admin file picker supports compose attachment context'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'const context = state.filePickerContext || '\''files-admin'\'';' 'shared file picker branches by context'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'const work = context === '\''compose-attachment'\''' 'compose/file-admin picker routing exists'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'if (!composeSectionVisible()) {' 'admin paste guard requires compose section visible'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'if (isEditableTarget(event.target)) {' 'admin paste guard skips editable controls'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'const images = clipboardImageFiles(event);' 'admin paste handler reads clipboard images'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'handleDroppedFiles(images, '\''upload-media'\'')' 'admin paste upload routes to compose uploader'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'if (mime.indexOf('\''image/'\'') === 0 || mime.indexOf('\''video/'\'') === 0) {' 'admin dropped files infer upload-media from image/video'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'targetType = '\''audio-note'\'';' 'admin dropped files infer audio-note from audio mime'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" 'targetType = '\''attachment'\'';' 'admin dropped files infer attachment from other mime'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" "const data = await uploadFileWithProgress(file, {" 'admin uploader uses upload progress path'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" "kind: kind || 'file'," 'admin uploader passes upload kind'
assert_file_contains "$SITE_SOURCE_ROOT/static/admin.js" "els.postContent.placeholder = '# Write in Markdown\\n\\nDrop images anywhere on this page to upload + insert.';" 'admin longform placeholder preserves drag/paste hint'

# Blog inline compose runtime behavior.
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "var COMPOSE_POST_TYPES = ['shortform', 'longform', 'capture-media', 'upload-media', 'attachment', 'audio-note', 'link-share', 'go-live'];" 'blog page defines full compose post type set'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "publishDestination: 'local_only'," 'blog compose defaults destination to local only'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "return 'local_only';" 'blog compose destination normalizer defaults to local only'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "btn('shortform', 'Shortform Post', false)" 'blog compose has shortform pill'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "btn('longform', 'Longform Post', false)" 'blog compose has longform pill'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "btn('capture-media', 'Take Photo/Video', false)" 'blog compose has capture-media pill'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "btn('upload-media', 'Upload Photo/Video', false)" 'blog compose has upload-media pill'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "btn('attachment', 'Upload Attachment/File', false)" 'blog compose has attachment pill'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "btn('audio-note', 'Audio Note', false)" 'blog compose has audio-note pill'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "btn('link-share', 'Link', false)" 'blog compose has link pill'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "btn('go-live', 'Go Live', true)" 'blog compose has disabled go-live pill'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'function composePostTypeIconSvg(type) {' 'blog compose defines icon renderer for post type pills'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "return '<div class=\"post-summary\">' + markdownBlock(text) + readMore + '</div>';" 'blog index renders condensed previews as block markdown'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'post-summary-read-more' 'blog index includes Read more link for truncated condensed previews'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'function postDateHtml(post, fallback)' 'blog feed renders date with hover title helper'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'function postHeaderMetaHtml(post, author, readMinutes, fallbackDate)' 'blog feed uses a shared post header metadata helper'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'published_timestamp ||' 'blog feed prefers server long timestamp for hover title'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'function composeNostrTarget(postType) {' 'blog compose defines nostr target mapper'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'function setComposeShortformLimit(raw, opts) {' 'blog compose supports editable shortform limits'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'data-compose-action="shortform-limit-toggle"' 'blog compose renders shortform counter toggle'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'data-compose-field="shortform-limit"' 'blog compose renders shortform custom limit input'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'function composeTextareaRows(postType) {' 'blog compose calculates per-type textarea height'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'if (type === '\''shortform'\'') {' 'blog compose has shortform-specific textarea sizing'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "if (actionName === 'audio-record-toggle')" 'blog compose exposes audio recorder action'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'new MediaRecorder(stream' 'blog compose uses MediaRecorder for audio-note mode'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'function preferredComposeAudioMimeType() {' 'blog compose picks supported audio recorder mime types'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'Press Start Recording to request microphone access.' 'blog compose audio mode gives explicit permission prompt guidance'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "root.classList.remove('blog-camera-mode');" 'camera mode no longer hides entire page content'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'compose-nostr-target-row' 'blog compose renders nostr target row under post-type selector'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'class="compose-post-type-icon"' 'blog compose icons render in segmented controls'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'aria-label="' 'blog compose icon controls keep accessible labels'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "setComposeOutput('Go Live is a future feature.', 'warn');" 'blog compose reports go-live as future feature'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'post_type: fields.postType,' 'blog compose payload includes post_type'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "title: fields.postType === 'shortform' ? '' : fields.title.trim()," 'blog compose sends empty title for shortform payloads'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "blog-compose-title-row\"' + (showTitleField ? '' : ' hidden aria-hidden=\"true\"')" 'blog compose hides title row when shortform is selected'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "state.compose.postType = 'longform';" 'blog compose reset restores longform default'
assert_file_contains "$SITE_SOURCE_ROOT/static/post-context.js" "title: postType === 'shortform' ? '' : String(inlineEditState.title || '').trim()," 'inline post editor sends empty title for shortform payloads'
assert_file_contains "$SITE_SOURCE_ROOT/static/post-context.js" "blog-compose-title-row\"' + (showTitleField ? '' : ' hidden aria-hidden=\"true\"')" 'inline post editor hides title row when shortform is selected'
assert_file_contains "$SITE_SOURCE_ROOT/static/post-context.js" 'function postDateHtml(current, className)' 'single post context renderer preserves date hover title helper'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'data-compose-action="capture-photo"' 'blog compose camera mode has capture action'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'data-compose-action="open-mode-picker"' 'blog compose mode panels provide picker action'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'data-compose-mode-target="upload-media"' 'blog compose upload-media panel opens media picker'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'data-compose-mode-target="attachment"' 'blog compose attachment panel opens file picker'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'data-compose-field="capture-upload"' 'blog compose includes capture input'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'data-compose-field="media-upload"' 'blog compose includes upload-media input'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'data-compose-field="file-upload"' 'blog compose includes file input'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'data-compose-field="audio-upload"' 'blog compose includes audio input'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'if (!isAdmin()) {' 'blog paste guard requires admin auth'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'if (isEditableTarget(event.target)) {' 'blog paste guard skips editable controls'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'if (!state.compose.open) {' 'blog paste handler opens compose when closed'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'setComposeOpen(true);' 'blog paste handler opens compose card'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "setComposePostType('upload-media', { skipAutosave: true, skipRender: true });" 'blog paste handler switches to upload-media type'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "handleComposeUploads(images, 'upload-media');" 'blog paste handler uploads pasted images'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "return apiPost('/cgi/blog-upload-media', {" 'blog upload flow posts to upload endpoint'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "filename: String((file && file.name) || 'upload.bin')," 'blog upload flow sends filename'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "mime_type: String((file && file.type) || '')," 'blog upload flow sends mime type'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "data_base64: String(dataUrl || '')" 'blog upload flow sends base64 payload'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'function composeCameraOverlayHtml() {' 'blog compose defines fullscreen camera overlay renderer'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'data-compose-camera-fullscreen-preview' 'blog compose camera overlay renders fullscreen video preview'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'function openComposeCameraCapture(options) {' 'blog compose has camera fullscreen entrypoint'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'state.compose.cameraFullscreen = true;' 'blog compose enables fullscreen camera mode'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'state.compose.cameraReturnToChooser = !!opts.returnToChooser;' 'blog compose tracks whether cancel should return to chooser'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'function closeComposeCameraCapture(options) {' 'blog compose has camera fullscreen exitpoint'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "if (state.compose.cameraFullscreen && event.key === 'Escape') {" 'blog compose allows escape to exit fullscreen camera'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "var forcePreview = postType === 'capture-media' || postType === 'upload-media';" 'blog compose forces preview visibility for media post types'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" "'<div class=\"blog-compose-islands\">' + composeCardHtml + previewCardHtml + '</div>'" 'blog compose renders wide preview as second island'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'blog-compose-preview-card' 'blog compose defines dedicated preview island card'
assert_file_contains "$SITE_SOURCE_ROOT/static/blog-page.js" 'aria-pressed="' + previewTogglePressed + '"' 'blog compose preview toggle exposes pressed state'

# Blog compose and mobile style contracts.
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '.blog-compose-card .compose-post-type-toolbar {' 'blog style defines post type toolbar'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" 'white-space: pre-wrap;' 'blog condensed previews preserve whitespace in rendered cards'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '.post-summary-read-more {' 'blog style defines compact Read more link'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '.blog-compose-card .compose-post-type-pill {' 'blog style defines post type pills'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" 'border-radius: 999px;' 'blog post type segmented control uses one continuous pill shell'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" 'gap: 0;' 'blog post type segmented control removes inter-button gaps'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" 'border-right: 1px solid var(--border);' 'blog segmented control uses internal separators'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '.blog-compose-card .compose-post-type-pill.is-active {' 'blog segmented control has explicit active/depressed state'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '.blog-compose-card .compose-nostr-target-row {' 'blog style defines nostr target row'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '.blog-compose-card .nostr-target-pill {' 'blog style defines nostr target pill'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '.blog-compose-shortform-meter {' 'blog style defines shortform counter row'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '.blog-compose-card .compose-audio-status {' 'blog style defines audio recorder status text'
assert_file_not_contains "$SITE_SOURCE_ROOT/static/style.css" '#blog-page-root.blog-camera-mode #blog-post-list' 'camera mode does not hide post list content'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '.blog-compose-card .compose-media-tools {' 'blog style defines media tools container'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '.blog-compose-card .compose-link-fields {' 'blog style defines link-share fields'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '.blog-compose-title-row {' 'blog style defines title + preview row layout'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '.blog-compose-islands {' 'blog style defines two-island compose/preview layout'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '.blog-compose-preview-card {' 'blog style defines separate preview island card'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '.blog-compose-card .blog-compose-preview-toggle[aria-pressed="true"]' 'blog style highlights active preview toggle'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" 'body.blog-camera-mode-active {' 'blog style locks page scroll in fullscreen camera mode'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '.blog-compose-camera-overlay {' 'blog style defines fullscreen camera overlay shell'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '@media (max-width: 900px) {' 'blog style has tablet/mobile breakpoint'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '.blog-compose-card .compose-post-type-toolbar {' 'mobile breakpoint keeps toolbar style available'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" 'overflow-x: auto;' 'mobile toolbar can scroll horizontally'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '@media (max-width: 640px) {' 'blog style has small-phone breakpoint'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '.blog-compose-card .compose-media-actions {' 'small-phone layout adjusts media action layout'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" 'grid-template-columns: repeat(2, minmax(0, 1fr));' 'small-phone media action grid is bounded and legible'
assert_file_not_contains "$SITE_SOURCE_ROOT/static/style.css" '.blog-compose-card .compose-post-type-pill { width: 100%;' 'compose pills are not forced to full width'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" 'Final mobile nav safety: prevent search/actions from covering center links.' 'mobile nav overlap safety block exists'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" '@media (max-width: 700px) {' 'mobile nav safety breakpoint exists'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" 'nav.site-nav {' 'mobile nav safety targets nav container'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" 'display: grid !important;' 'mobile nav safety uses grid to separate rows'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" 'grid-template-rows: auto auto;' 'mobile nav safety splits nav into two rows'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" 'nav.site-nav .nav-center {' 'mobile nav safety styles center links row'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" 'overflow-x: auto !important;' 'mobile nav center remains scrollable without overlap'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" 'nav.site-nav .nav-right {' 'mobile nav safety styles right controls row'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" 'grid-row: 2;' 'mobile nav right controls pinned to second row'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" 'nav.site-nav .nav-search {' 'mobile nav safety styles search shell'
assert_file_contains "$SITE_SOURCE_ROOT/static/style.css" 'flex: 1 1 12rem !important;' 'mobile nav search remains bounded in second row'

if [ "$FAIL_COUNT" -gt 0 ]; then
  printf 'FAIL: %s tests failed; %s passed\n' "$FAIL_COUNT" "$PASS_COUNT" >&2
  exit 1
fi

printf 'ok (%s assertions)\n' "$PASS_COUNT"
