# Server requirements for the nostr-blog template.
jq=required
pandoc=required
nostril=required
syncthing=optional
bitcoin=required
lightning=required
stonr=required
nostr_identity=required
stonr_relay=required
btcpay=optional
