# Server requirements for the nostr-blog template.
support_tools=required
syncthing=optional
bitcoin_node=required
lightning_node=required
nostr_identity=required
zaps_feature=required
stonr_relay=required
btcpay=optional
