# Server requirements for the nostr-blog template.
support_tools=required
syncthing=optional
bitcoin_node=optional
lightning_node=optional
zap_endpoint=optional
nostr_identity=required
zaps_feature=required
stonr=required
stonr_relay=required
authored_nostr_content=required
watchtower_remote=optional
video_chat_backend=optional
