read list-public-posts
read list-navbar-pages
read btc-usd-rate
read blog-archive
read blog-index
read blog-search
read blog-tags
admin-read blog-list-pages
commerce-read blog-get-product
nostr-read blog-comments
nostr-read blog-post-context
admin blog-manage-post
admin blog-upload-media
admin blog-save-post
admin blog-publish-nostr-page
admin blog-video-chat-control
admin blog-secure-chat-admin
admin blog-payments
